import { ReactNode } from "react";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

import { cn } from "@/lib/utils";

import Header from "@/components/Global/Header";
import Footer from "@/components/Global/Footer";

import "./globals.css";
import { headers } from "next/headers";

const fontSans = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children
}: Readonly<{
  children: ReactNode;
}>) {
  const url = headers().get('x-url');
  const showHeaderFooter = !url?.includes('/login');
  return (
    <html lang="en">
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased",
          fontSans.variable
        )}
      >
        {showHeaderFooter && <Header />}
        {children}
        {showHeaderFooter && <Footer />}
      </body>
    </html>
  );
}
